version: "3.1"
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
    ports:
      - 3306:3306
  pawnshop:
    depends_on:
      - db
    image: pawnshop:1.0
    ports:
      - 8082:8082
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=db
      - DATABASE_PORT=3306